In [7]:
import pandas as pd

In [2]:
# 1:
df = pd.read_csv("MN.csv")

In [3]:
df.loc[:, ["title", "rating"]]

      title  rating
0    Dangal       8
1  3 Idiots       9
2     vivah      10
3     ready       9
4      DDLJ       5

In [22]:
# 2:
df = pd.DataFrame({
    "Product_name": ["Bag", "ear rings", "iphone", "gold", "diamond", "silver", "shoes", "socks", "charger", "watch"],
    "Category": ["Fashion", "Fashion", "electronic", "jewellery", "jewellery", "fashion", "fashion", "fashion", "accessories", "accessories"],
    "Price": [2000, 500, 100000, 500000, 5000000, 5000, 2000, 300, 150, 600]
 })

In [23]:
df.iloc[:10, :]

  Product_name     Category    Price
0          Bag      Fashion     2000
1    ear rings      Fashion      500
2       iphone   electronic   100000
3         gold    jewellery   500000
4      diamond    jewellery  5000000
5       silver      fashion     5000
6        shoes      fashion     2000
7        socks      fashion      300
8      charger  accessories      150
9        watch  accessories      600

In [24]:
# 3:
df = pd.DataFrame({
    "restaurant" : ["Dominos", "Pizza hut", "Devils Burger", "Ajay's"],
    "order_amount" : [400, 500, 800, 950],
    "delivery_time" : [10, 15, 35, 40]
})

In [25]:
df[df.order_amount>500]

      restaurant  order_amount  delivery_time
2  Devils Burger           800             35
3         Ajay's           950             40

In [27]:
# 4:
df = pd.DataFrame({
    "song": ["Song A", "Song B", "Song C", "Song D", "Song E"],
    "artist": ["Artist 1", "Artist 2", "Artist 3", "Artist 4", "Artist 5"],
    "streams": [2000000, 500000, 3000000, 1500000, 800000],
    "duration": [150, 120, 200, 170, 160]
})

In [28]:
df.query("streams > 1000000 and duration < 180")

     song    artist  streams  duration
0  Song A  Artist 1  2000000       150
3  Song D  Artist 4  1500000       170

In [30]:
 # 5:
df = pd.DataFrame({
    "team1": ["MI", "CSK", "RCB", "KKR", "DC", "RR"],
    "team2": ["CSK", "RCB", "KKR", "DC", "RR", "MI"],
    "winner": ["MI", "CSK", "RCB", "KKR", "DC", "RR"],
    "total_runs": [190, 175, 210, 220, 150, 200]
})

In [31]:
df[(df["total_runs"] >= 180) & (df["total_runs"] <= 220)]

  team1 team2 winner  total_runs
0    MI   CSK     MI         190
2   RCB   KKR    RCB         210
3   KKR    DC    KKR         220
5    RR    MI     RR         200